// <auto-generated />
namespace BankingProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CreateNewAccountInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateNewAccountInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202410201456098_CreateNewAccountInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
