// <auto-generated />
namespace BankingProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AtmC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AtmC));
        
        string IMigrationMetadata.Id
        {
            get { return "202412261457096_AtmC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
